
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;

public class InputAssignment extends JDialog {

    /**
     * Creates new form InputAssignment
     */
    MainGUI caller;

    public InputAssignment(java.awt.Frame parent, boolean modal, MainGUI caller) {
        super(parent, modal);
        this.caller = caller;
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    public InputAssignment(java.awt.Frame parent, boolean modal, CalendarDate date, MainGUI caller) {
        this(parent, modal, caller);
        preFillComponents(date);
        this.caller = caller;
    }
    
    private void preFillComponents(CalendarDate date) {
        dayField.setText(String.valueOf(date.getSelectedDay()));
        monthField.setText(String.valueOf(date.getSelectedMonth() + 1));
        yearField.setText(String.valueOf(date.getSelectedYear()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assignmentName = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        priorityLevel = new java.awt.Choice();priorityLevel.add("High");priorityLevel.add("Medium");priorityLevel.add("Low") ;
        monthField = new javax.swing.JTextField();
        dayField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estimatedCompletionTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        activityType = new java.awt.Choice();activityType.add("Academic");activityType.add("Extracurricular");activityType.add("Miscellaneous");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activity Editor");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Activity Editor");

        doneButton.setBackground(new java.awt.Color(51, 255, 51));
        doneButton.setText("Save");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("/");

        jLabel3.setText("/");

        jLabel4.setText("Activity Name");

        jLabel5.setText("Estimated Completion Time (minutes)");

        jLabel6.setText("Priority Level");

        jLabel7.setText("Due Date (mm/dd/yyyy)");

        jLabel8.setText("Activity Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(activityType, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(assignmentName)
                            .addComponent(priorityLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(estimatedCompletionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedCompletionTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priorityLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(activityType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed

        try {
           
            String name = assignmentName.getText();
            int time = Integer.parseInt(estimatedCompletionTime.getText());
            String priority = priorityLevel.getSelectedItem();
            String type = activityType.getSelectedItem();
            int day = Integer.parseInt(dayField.getText());
            int month = Integer.parseInt(monthField.getText());
            int year = Integer.parseInt(yearField.getText());
            int lastID = 0;

            ResultSet rs = MainGUI.getResultSet();
            Statement stmt = MainGUI.getStatement();
            
            String SQL = "SELECT * FROM Events";
            rs = stmt.executeQuery(SQL);

            rs.last();
            lastID = rs.getInt("ID");
            
            Assignment newAssignment = new Assignment(lastID + 1, name, time, priority, type, month, day, year);
            System.out.println("New assignment added with priority score: " + newAssignment.getPriorityScore());
            
            rs.moveToInsertRow();
            rs.updateString("Assignment_Name", newAssignment.getName());
            rs.updateString("Priority_Level", newAssignment.getPriority());
            rs.updateString("Priority_Level", newAssignment.getPriority());
            rs.updateString("Event_Type", newAssignment.getType());
            rs.updateInt("ID", newAssignment.getID());
            rs.updateInt("Estimated_Time", time);
            rs.updateInt("Due_Month", newAssignment.getDate().getSelectedMonth());
            rs.updateInt("Due_Day", newAssignment.getDate().getSelectedDay());
            rs.updateInt("Due_Year", newAssignment.getDate().getSelectedYear());
            rs.insertRow();
            stmt.close();
            rs.close();
            MainGUI.connect();
            //JOptionPane.showMessageDialog(this, "Record Saved");
            
            caller.refreshCalendar(newAssignment.getDate().getSelectedMonth() - 1, newAssignment.getDate().getSelectedYear());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sorry, there was an error with the data input. Please correct the error and try again.");
            System.out.println("Error: " + e.getMessage());
        }

        Component component = (Component) evt.getSource();
        JDialog dialog = (JDialog) javax.swing.SwingUtilities.getRoot(component);
        dialog.dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice activityType;
    private javax.swing.JTextField assignmentName;
    private javax.swing.JTextField dayField;
    private javax.swing.JButton doneButton;
    private javax.swing.JTextField estimatedCompletionTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField monthField;
    private java.awt.Choice priorityLevel;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
